name: gitartwork from a contribution graph
on: 
  push:
  schedule:
    - cron: '* */24 * * *'
jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate gitartwork
        id: generate-artwork
        uses: priya-mandyal/gitartwork@v1
        with: 
          user_name: priya-mandyal
          text: HI, I AM PRIYA
        continue-on-error: true

      - name: Push changes
        if: steps.generate-artwork.outcome == 'success'
        uses: priya-mandyal/simple-push-action@v1
